### ISSUE TITLE
Clone leave roles empty

### ISSUE THREAD

**Issue by neilhwatson** [OldCrowEW/dcos-ansible#12]
Some odd about this repo:

neil@luna:~/src/neil/dcos$ git clone git@github.com:OldCrowEW/dcos-ansible.git
Cloning into 'dcos-ansible'...
remote: Counting objects: 282, done.
remote: Total 282 (delta 0), reused 0 (delta 0), pack-reused 282
Receiving objects: 100% (282/282), 27.68 KiB | 0 bytes/s, done.
Resolving deltas: 100% (117/117), done.
Checking connectivity... done.

neil@luna:~/src/neil/dcos$ find dcos-ansible/roles/
dcos-ansible/roles/
dcos-ansible/roles/ansible-dcos-bootstrap-master
dcos-ansible/roles/ansible-dcos-common
dcos-ansible/roles/ansible-dcos-bootstrap-agent
dcos-ansible/roles/ansible-dcos-bootstrap-node

**Comment by OldCrowEW** [comment]
@neilhwatson I commented on your other [issue ](https://github.com/OldCrowEW/ansible-dcos-bootstrap-agent/issues/1)before I saw this. 

You are running into issues because of git submodules. I broke up the playbook so it could be consumed easier as [Ansible Galaxy roles](https://galaxy.ansible.com/OldCrowEW/). If you would like to git clone give this a try:

`git clone --recursive git@github.com:OldCrowEW/dcos-ansible.git`

For already cloned repos:

`git clone git@github.com:OldCrowEW/dcos-ansible.git`
`cd dcos-ansible`
`git submodule update --init --recursive`

Hope this helps.
